service: client-indep-secure

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

  stage: dev
  region: eu-central-1
  memorySize: 2048
  timeout: 500 # Note: API Gateway current maximum is 30 seconds
  ecr:
    images:
      baseimage:
        path: .
  apiGateway:
    apiKeys:
      - invoker-key-indep-1
  httpApi:
    authorizers:
      # WARNING: DO NOT PUT ANYTHING HERE OR BELOW FOR DEPLOYMENT SCRIPT TO WORK
      jwtAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1234
        audience:
          - 1234


functions:
  hello:
    image: baseimage
    events:
      - httpApi:
          path: federated/client-indep-secure
          method: POST
          integration: lambda-proxy
          #private: true
          authorizer:
            name: jwtAuthorizer
            scopes:
              - client-functions/invoke

# WARNING: DO NOT PUT ANYTHING HERE OR BELOW FOR DEPLOYMENT SCRIPT TO WORK
