apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  labels:
    app: parameter-server-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: parameter-server
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{.Values.mongodbPort}}
      nodePort: {{ .Values.service.port }}
      protocol: TCP
