service: client-indep

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

  stage: dev
  region: eu-central-1
  memorySize: 2048
  timeout: 500 # Note: API Gateway current maximum is 30 seconds
  ecr:
    images:
      baseimage:
        path: .
  apiGateway:
    apiKeys:
      - invoker-key-indep

functions:
  hello:
    image: baseimage
    events:
      - http:
          path: federated/client-indep
          method: post
          integration: lambda-proxy
          private: true

# WARNING: DO NOT PUT ANYTHING HERE OR BELOW FOR DEPLOYMENT SCRIPT TO WORK
